### ISSUE TITLE
Templated list classes

### ISSUE THREAD

**Issue by richfitz** [richfitz/RcppR6#15]
e.g.,

```yaml
templated:
  name_cpp: "examples::templated<T>"
  templates:
    parameters: T
    concrete:
      - ["int": "int"]
      - ["double": "double"]
  list:
    - n_elements: int
    - list: "std::vector<int>"
```
