### ISSUE TITLE
templated class generation fails when none are renamed

### ISSUE THREAD

**Issue by richfitz** [richfitz/RcppR6#3]
This is OK:
```yaml
  templates:
    parameters: covfn_type
    concrete:
      - ["matern32": covfn_matern32]
      - ["squaredexp": covfn_squaredexp]
```

This fails:

```yaml
  templates:
    parameters: T
    concrete:
      - covfn_matern32
      - covfn_squaredexp
```
